version: '2.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    scale: 2
    expose:
      - "8080"
    links:
      - db

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
